# Code generated by:
# python -m pwiz --engine=postgresql --user=root --host=localhost --schema=speed_daemon --info --preserve-order --password protohackers
# Date: March 17, 2024 12:49PM
# Database: protohackers
# Peewee version: 3.17.1

from peewee import *
from playhouse.postgres_ext import *

database = PostgresqlDatabase(
    "protohackers", **{"host": "localhost", "user": "root", "password": "root"}
)


class UnknownField(object):
    def __init__(self, *_, **__):
        pass


class BaseModel(Model):
    class Meta:
        database = database


class User(BaseModel):
    peer = CharField(index=True, null=True)
    connected_at = DateTimeField(null=True)
    disconnected_at = DateTimeField(null=True)
    heartbeat_requested_at = DateTimeField(null=True)

    class Meta:
        table_name = "User"
        schema = "speed_daemon"


class Camera(BaseModel):
    user = ForeignKeyField(column_name="user_id", field="id", model=User, null=True)
    road = IntegerField(null=True)
    mile = IntegerField(null=True)
    limit = IntegerField(null=True)

    class Meta:
        table_name = "Camera"
        schema = "speed_daemon"


class Dispatcher(BaseModel):
    user = ForeignKeyField(column_name="user_id", field="id", model=User, null=True)
    roads = ArrayField(field_class=IntegerField, null=True)

    class Meta:
        table_name = "Dispatcher"
        schema = "speed_daemon"


class Observation(BaseModel):
    camera = ForeignKeyField(
        column_name="camera_id", field="id", model=Camera, null=True
    )
    plate = CharField(index=True, null=True)
    timestamp = DateTimeField(null=True)

    class Meta:
        table_name = "Observation"
        schema = "speed_daemon"


class Ticket(BaseModel):
    plate = CharField(index=True, null=True)
    road = IntegerField(null=True)
    mile1 = IntegerField(null=True)
    timestamp1 = DateTimeField(null=True)
    mile2 = IntegerField(null=True)
    timestamp2 = DateTimeField(null=True)
    speed = DecimalField(null=True)
    delivered_to = ForeignKeyField(
        column_name="delivered_to", field="id", model=Dispatcher, null=True
    )
    delivered_at = DateTimeField(null=True)

    class Meta:
        table_name = "Ticket"
        schema = "speed_daemon"
