app = "protohackers-aalekhpatel07"

[[services]]
    internal_port = 12000
    protocol = 'tcp'

    [[services.ports]]
        handlers = ['tls']
        port = 12000
    [[services.tcp_checks]]
        grace_period = "1s"
        interval = "60s"
        restart_limit = 0
        timeout = "2s"
