[workspace]
members = [
  "echo-server",
  "prime-time",
  "budget-chat",
  "unusual-database-program",
  "mob-in-the-middle",
]

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev]
codegen-units = 4
